# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 개발일상
email: develop.leoh7@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leoh7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  leoh7

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

paginate: 3
navigation: True

# Disqus
disqus: True
disqus_url: https://disqus.com/by/88_rafael/
disqus_id: 88rafael
disqus_shortname: 88rafael

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

destination: ./output/

### default 레이아웃 정의하기
# 이런식으로 사용이 가능하다
# defaults:
#   -
#     scope:    # scope/values 쌍을 생성할 때, type 은 선택사항이지만 path 는 반드시 정의해야 합니다.
#       path: ""
#       type: "pages"
#     values:
#       layout: "my-site"
#   -
#     scope:
#       path: "projects"
#       type: "pages" # 이전 Jekyll 2.2 에서는 `page` 
#     values:
#       layout: "project" # 이전 디폴트 레이아웃 설정을 덮어씀
#       author: "Mr. Hyde"
# 이 디폴트 값으로 인하여, 모든 페이지는 my-site 레이아웃을 사용하게 됩니다. 
# projects/ 폴더 안에 있는 모든 HTML 파일들은 project 레이아웃을 사용하게 됩니다. 
# 또한 이 파일들은 Mr. Hyde 라는 값을 가진 Liquid 변수 page.author 도 갖게 됩니다.

defaults:
  -
    scope:
      path: "" # 이 빈 문자열은 프로젝트의 모든 파일을 의미함
      type: "posts" # 이전 Jekyll 2.2 에서는 `post`
    values:
      layout: "default"
      comments: true